stages:
  - build
  - deploy

variables:
  NODE_VERSION: "22"

before_script:
  - apt-get update -y
  - apt-get install -y openssh-client

build-job:
  stage: build
  image: node:$NODE_VERSION
  script:
    - npm install
    - npm run generate
    - ls -la dist/  # Vérification du contenu généré
  artifacts:
    paths:
      - dist/
    expire_in: 1 week

deploy-to-vps:
  stage: deploy
  only:
    - main
  script:
    - mkdir -p ~/.ssh
    - echo "$VPS_SSH_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H $VPS_HOST >> ~/.ssh/known_hosts
    - ls -la /builds/leoteissier/portfolio/.output/public  # Vérifiez le contenu réel du répertoire de sortie
    - if [ -z "$(ls -A /builds/leoteissier/portfolio/.output/public)" ]; then echo "Le répertoire public est vide. Annulation du déploiement."; exit 1; fi
    - ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST "sudo rm -rf /var/www/portfolio/*"
    - scp -o StrictHostKeyChecking=no -r /builds/leoteissier/portfolio/.output/public/* $VPS_USER@$VPS_HOST:/var/www/portfolio/
  dependencies:
    - build-job
  environment:
    name: production
    url: http://$VPS_HOST
