stages:
  - build
  - deploy

# Variables for Docker, SSH, and the VPS
variables:
  DOCKER_IMAGE_PROD: "portfolio-app-prod"
  VPS_USER: $VPS_USER
  VPS_HOST: $VPS_HOST
  VPS_PATH: "/var/www"

build_job:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    # Construire l'image Docker avec le Dockerfile de production
    - docker build -f Dockerfile.prod -t $DOCKER_IMAGE_PROD .
    # Sauvegarder l'image en un fichier compressé
    - docker save $DOCKER_IMAGE_PROD | gzip > portfolio.tar.gz
  artifacts:
    paths:
      - portfolio.tar.gz

deploy_job:
  stage: deploy
  before_script:
    # Setup SSH key for remote server access
    - 'which ssh-agent || ( apk add --update openssh )'
    - eval $(ssh-agent -s)
    - echo "$VPS_SSH_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  script:
    # Supprimer le fichier portfolio.tar.gz existant sur le VPS
    - ssh $VPS_USER@$VPS_HOST "rm -f $VPS_PATH/portfolio.tar.gz"
    
    # Copier le fichier image Docker sur le VPS
    - scp portfolio.tar.gz $VPS_USER@$VPS_HOST:$VPS_PATH

    # Charger la nouvelle image Docker sur le VPS
    - ssh $VPS_USER@$VPS_HOST "docker load -i $VPS_PATH/portfolio.tar.gz"

    # Arrêter et supprimer le conteneur existant s'il est en cours d'exécution
    - ssh $VPS_USER@$VPS_HOST "docker stop portfolio || true && docker rm portfolio || true"

    # Démarrer un nouveau conteneur avec la nouvelle image
    - ssh $VPS_USER@$VPS_HOST "docker run -d --name portfolio -p 3000:3000 $DOCKER_IMAGE_PROD"
  only:
    - main  # Exécuté uniquement lors d'un push sur la branche main
