stages:
  - build_dev
  - build_prod
  - deploy_prod

# Variables pour le build et le déploiement
variables:
  DOCKER_IMAGE_DEV: "portfolio-app-dev"
  DOCKER_IMAGE_PROD: "portfolio-app-prod"
  VPS_USER: $VPS_USER  # Défini dans les variables CI/CD de GitLab
  VPS_HOST: $VPS_HOST  # Défini dans les variables CI/CD de GitLab
  VPS_SSH_KEY: $VPS_SSH_KEY  # Clé SSH privée pour la connexion

# Job de build pour l'environnement de développement
build_dev:
  stage: build_dev
  image: docker:latest
  script:
    - docker build -f Dockerfile.dev -t $DOCKER_IMAGE_DEV .
  only:
    - develop  # Cela s'exécutera uniquement sur la branche "develop"
  artifacts:
    paths:
      - portfolio-app-dev.tar.gz

# Job de build pour l'environnement de production
build_prod:
  stage: build_prod
  image: docker:latest
  script:
    - docker build -f Dockerfile.prod -t $DOCKER_IMAGE_PROD .
    - docker save $DOCKER_IMAGE_PROD | gzip > portfolio-app-prod.tar.gz
  only:
    - main  # Exécuté uniquement sur la branche "main"
  artifacts:
    paths:
      - portfolio-app-prod.tar.gz

# Job de déploiement pour la production
deploy_prod:
  stage: deploy_prod
  before_script:
    # Configuration de la clé SSH pour la connexion au VPS
    - 'which ssh-agent || ( apk add --update openssh )'
    - eval $(ssh-agent -s)
    - echo "$VPS_SSH_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  script:
    # Copier l'image sur le serveur
    - scp portfolio-app-prod.tar.gz $VPS_USER@$VPS_HOST:/var/www
    # Charger l'image Docker et lancer le conteneur
    - ssh $VPS_USER@$VPS_HOST "docker load -i /var/www/portfolio-app-prod.tar.gz && docker stop portfolio-app-prod || true && docker rm portfolio-app-prod || true && docker run -d --name portfolio-app-prod -p 3000:3000 $DOCKER_IMAGE_PROD"
  only:
    - main  # Déploiement uniquement à partir de la branche "main"
