name: Build and Deploy Portfolio

on:
  push:
    branches:
      - main

jobs:
  build-and-generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Generate static files
        run: npm run generate

      - name: Verify dist directory
        run: ls -la dist

  deploy:
    needs: build-and-generate
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Deploy to VPS
        run: |
          scp -o StrictHostKeyChecking=no -r dist/* mmi21c14@mmi21c14.mmi-troyes.fr:/var/www/portfolio/
          ssh -o StrictHostKeyChecking=no mmi21c14@mmi21c14.mmi-troyes.fr "
            sudo rm -rf /var/www/portfolio/* &&
            sudo mv /var/www/portfolio/next /var/www/portfolio
          "